# Generated by Django 4.2.30 on 2026-06-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('analysis', '0001_initial'),
        ('staff', '0002_restructure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcriptionrecord',
            options={'ordering': ['-record_datetime'], 'verbose_name': 'Transcription Record', 'verbose_name_plural': 'Transcription Records'},
        ),
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Тарифный пакет компании', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Отдел сотрудника (для динамических промптов)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='analysis.department'),
        ),
        migrations.AlterField(
            model_name='employeegroup',
            name='accesses',
            field=models.JSONField(blank=True, default=list, help_text='Список доступов: view_calls, upload_calls, analyze_calls, ...'),
        ),
    ]
