# Generated by Django 4.2.30 on 2026-06-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_transcriptionrecord_options_company_plan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanySettings',
        ),
    ]
