# Generated by Django 4.2.30 on 2026-06-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_promptlist_analysiscriterion_prompt_list'),
        ('staff', '0004_delete_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroup',
            name='prompt_lists',
            field=models.ManyToManyField(blank=True, help_text='Списки промптов, назначенные группе.', related_name='groups', to='analysis.promptlist'),
        ),
        migrations.AddField(
            model_name='transcriptionrecord',
            name='is_original',
            field=models.BooleanField(default=False, help_text='Сплошной оригинал сессии (от-до), без транскрибации.'),
        ),
        migrations.AddField(
            model_name='transcriptionrecord',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID сессии записи — связывает сегменты с цельным оригиналом.', max_length=64),
        ),
    ]
