# Generated by Django 4.2.30 on 2026-06-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_employeegroup_prompt_lists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание инцидента'),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(blank=True, default='', help_text='Важность: low/medium/high', max_length=20),
        ),
    ]
