# Generated by Django 4.2.30 on 2026-06-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_incident_description_incident_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionrecord',
            name='transcript_segments',
            field=models.JSONField(blank=True, default=list, help_text='Сегменты с таймингами: [{start,end,speaker,text}]'),
        ),
    ]
