# Generated by Django 4.2.30 on 2026-06-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='Максимум пользователей. Пусто = без ограничения.', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Цена пакета (за период).', max_digits=12)),
                ('features', models.JSONField(blank=True, default=dict, help_text='Набор фич, напр. {"analytics": true, "dynamic_prompts": true}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price', 'name'],
            },
        ),
    ]
