# Generated by Django 4.2.30 on 2026-06-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_type',
            field=models.CharField(choices=[('per_user', 'За сотрудника × ставка'), ('fixed', 'Фиксированная ставка')], default='fixed', help_text='Тип тарификации.', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ставка за одного сотрудника (для типа «за сотрудника»).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фиксированная цена за период (для типа «фикс»).', max_digits=12),
        ),
    ]
