# Generated by Django 4.2.30 on 2026-06-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_restructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='staff.company')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompanyAnalysisSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Глобально включить/выключить AI-анализ разговоров.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_settings', to='staff.company')),
            ],
            options={
                'verbose_name': 'Company Analysis Settings',
                'verbose_name_plural': 'Company Analysis Settings',
            },
        ),
        migrations.CreateModel(
            name='AnalysisCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название критерия, напр. «Вежливость».', max_length=255)),
                ('prompt_text', models.TextField(help_text='Инструкция для модели по этому критерию.')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_criteria', to='staff.company')),
                ('department', models.ForeignKey(blank=True, help_text='Пусто = применяется ко всем отделам компании.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='analysis.department')),
            ],
            options={
                'verbose_name': 'Analysis Criterion',
                'verbose_name_plural': 'Analysis Criteria',
                'ordering': ['order', 'id'],
            },
        ),
    ]
