# Generated by Django 4.2.30 on 2026-06-09 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_transcriptionrecord_options_company_plan_and_more'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysiscriterion',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Применять к группе сотрудников. Пусто = ко всем.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='staff.employeegroup'),
        ),
        migrations.AlterField(
            model_name='analysiscriterion',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Применять к отделу. Пусто = ко всем.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='analysis.department'),
        ),
    ]
