# Generated by Django 4.2.30 on 2026-06-16 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_delete_companysettings'),
        ('analysis', '0002_analysiscriterion_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_lists', to='staff.company')),
            ],
            options={
                'verbose_name': 'Prompt List',
                'verbose_name_plural': 'Prompt Lists',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='analysiscriterion',
            name='prompt_list',
            field=models.ForeignKey(blank=True, help_text='Список, к которому относится промпт.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='analysis.promptlist'),
        ),
    ]
