# Generated by Django 4.2.28 on 2026-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_call_twilio_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='callanalysis',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
