# Generated by Django 4.2.28 on 2026-03-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_add_category_to_callanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='callanalysis',
            name='transcript_dialogue',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
